stages:
  - build
  - archive

build_project:
  stage: build
  script:
    - xcodebuild test -project project-name -scheme project-name -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.2' | xcpretty -s
  tags:
    - ios_9-2
    - xcode_7-2
    - osx_10-11

archive_project:
  stage: archive
  script:
    - xcodebuild clean archive -archivePath build/Gitlab-CI-for-iOS -scheme GitLab-CI-for-iOS
    - xcodebuild -exportArchive -exportFormat ipa -archivePath "build/name" -exportPath "build/path"
  artifacts:
    paths:
    - build/path
  tags:
    - ios_9-2
    - xcode_7-2
    - osx_10-11
